//! `aleph-oracle`: oracle comparison harness against Qiskit Aer.
//!
//! Fixtures are generated by `oracle/gen.py` (committed under
//! `oracle/fixtures/`) and consumed at test time to assert that
//! `aleph` backends agree with Qiskit Aer to within `1e-10`.
//!
//! See `docs/superpowers/specs/2026-05-24-p0-10-oracle-qiskit-design.md`.

pub mod error;
pub mod fixture;
pub use error::OracleError;
pub use fixture::{
    load_fixture, load_qasm, workspace_path, Fixture, StateVectorFixture, SCHEMA_VERSION,
};
