//! `aleph-oracle`: oracle comparison harness against Qiskit Aer.
//!
//! Fixtures are generated by `oracle/gen.py` (committed under
//! `oracle/fixtures/`) and consumed at test time to assert that
//! `aleph` backends agree with Qiskit Aer to within `1e-10`.
//!
//! See `docs/superpowers/specs/2026-05-24-p0-10-oracle-qiskit-design.md`.

pub mod coverage;
pub mod error;
pub mod fixture;
pub mod harness;
pub mod state;
pub use error::OracleError;
pub use fixture::{
    load_fixture, load_qasm, workspace_path, Fixture, StateVectorFixture, SCHEMA_VERSION,
};
pub use harness::{
    run_distribution_oracle, run_state_oracle, run_state_oracle_with_tol, DISTRIBUTION_FLOOR,
    DISTRIBUTION_SHOTS, FP32_STATE_TOLERANCE, STATE_TOLERANCE,
};
pub use state::HasAmplitudes;
