[package]
name = "aleph-parser"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
aleph-core = { path = "../aleph-core" }
aleph-ir   = { path = "../aleph-ir" }
nom        = { workspace = true }
nom_locate = { workspace = true }
thiserror  = { workspace = true }
smallvec   = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
