[package]
name = "aleph-stab"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
aleph-core    = { path = "../aleph-core" }
aleph-backend = { path = "../aleph-backend" }
thiserror     = { workspace = true }
rand          = { workspace = true }

[dev-dependencies]
aleph-sv   = { path = "../aleph-sv" }
proptest   = { workspace = true }
criterion  = { workspace = true }

[[bench]]
name = "stab_clifford"
harness = false
