//! Per-fixture integration tests. The list of `#[test]` functions is
//! generated by `crates/aleph-oracle/build.rs` from
//! `oracle/fixtures/*.json`; one test per fixture, named after the
//! fixture's file stem.

include!(concat!(env!("OUT_DIR"), "/_generated.rs"));
