//! End-to-end smoke test that exercises the full oracle pipeline on
//! one fixture. The per-fixture test list is generated by `build.rs`
//! later — this file proves the moving parts work before then.

use aleph_oracle::{load_fixture, load_qasm, run_state_oracle, workspace_path};
use aleph_sv::NaiveSvBackend;

#[test]
fn identity_1q_matches_qiskit() {
    let fx = load_fixture(&workspace_path("oracle/fixtures/identity_1q.json"))
        .expect("load fixture");
    let qasm = load_qasm(&workspace_path("oracle/circuits/identity_1q.qasm"))
        .expect("load qasm");
    let mut backend = NaiveSvBackend::with_seed(0);
    run_state_oracle(&mut backend, &fx, &qasm).expect("oracle");
}
