"""Render docs/perf/qaoa.md from a qaoa-results.json (deterministic, pure).
Two tables: approximation ratio (n x p) and energy-eval timing (n x p x backend)."""
import argparse
import json
from pathlib import Path

CAVEAT = (
    "_Single-thread all backends. aleph via aleph-py (SV = NaiveSvBackend, "
    "MPS = MpsBackend χ=128), Qiskit via Aer save_expectation_value. **MPS is "
    "not expected to beat SV at n≤14** — the state vector is tiny (≤16K "
    "amplitudes), so SV constant factors win; MPS's crossover is at larger n "
    "(cf. VQE.md). Approximation ratio = optimized ⟨H_C⟩ / exact max-cut "
    "(COBYLA, best of N restarts); 3-regular QAOA ratio climbs with p (p=1≈0.7 "
    "is a sanity figure, not gated at 0.9)._"
)


def render(data, meta):
    w = data["workloads"]
    rows = sorted(w.values(), key=lambda r: (r["n"], r["p"]))
    ns = sorted({r["n"] for r in rows})
    ps = sorted({r["p"] for r in rows})
    out = ["# Phase 4 — QAOA Max-Cut (3-regular graphs)\n",
           "> Auto-generated by `scripts/qaoa/render_report.py`. Do not edit by hand.\n",
           f"**Date:** {meta['date']}  ", f"**Host:** {meta['host']}  ",
           f"**Toolchain:** {meta['toolchain']}\n", CAVEAT, "",
           "## Approximation ratio (optimized ⟨H_C⟩ / max-cut)\n",
           "| n | edges | max-cut | " + " | ".join(f"p={p}" for p in ps) + " |",
           "|--:|------:|--------:|" + "|".join("--:" for _ in ps) + "|"]
    by = {(r["n"], r["p"]): r for r in rows}
    for n in ns:
        any_r = next(r for r in rows if r["n"] == n)
        cells = []
        for p in ps:
            r = by.get((n, p), {})
            cells.append(f"{r['ratio']:.3f}" if "ratio" in r else "—")
        out.append(f"| {n} | {any_r['edges']} | {any_r['maxcut']} | " + " | ".join(cells) + " |")
    out += ["", "## Energy-eval time per call (ms), by backend\n",
            "| n | p | aleph SV | aleph MPS | Aer |",
            "|--:|--:|---------:|----------:|----:|"]
    for r in rows:
        def ms(k):
            return f"{r[k]:.3f}" if k in r else "—"
        out.append(f"| {r['n']} | {r['p']} | {ms('sv_ms')} | {ms('mps_ms')} | {ms('aer_ms')} |")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, type=Path)
    ap.add_argument("--meta", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()
    data = json.loads(args.results.read_text())
    meta = json.loads(args.meta.read_text())
    args.out.write_text(render(data, meta))
    print(f"[render] -> {args.out}")


if __name__ == "__main__":
    main()
