// Q6-01 (sim) — distance-3 rotated surface-code memory-Z decoder, lookup-table form.
//
// The smallest interesting QEC decoder as synthesisable RTL: an 8-bit syndrome (the d=3 memory-Z
// detectors) indexes a 256-entry ROM whose contents are the predicted flip of logical observable 0.
// The ROM is generated by the Rust Union-Find decoder (`examples/qec_d3_lut_table.rs`), so the
// hardware reproduces a *real* decoder's behaviour — not a toy. Larger codes cannot be tabulated
// (the table is exponential in the detector count); they get the Union-Find datapath in Q6-02. This
// module's job is to stand up the host-model -> RTL -> simulation flow end to end (the Q6-01
// "syndrome-in / correction-out skeleton") on hardware that also synthesises for the Kria KV260.
//
// Interface: a one-deep valid/valid streaming handshake. On `in_valid`, `syndrome` is latched and
// the looked-up correction appears on `correction` with `out_valid` one clock later (1-cycle
// latency — the figure of merit this whole track exists to minimise).

`timescale 1ns / 1ps

module surface_d3_decoder #(
    parameter int  SYNDROME_BITS = 8,
    parameter string MEM_FILE    = "surface_d3_lut.mem"
) (
    input  logic                     clk,
    input  logic                     rst_n,
    input  logic                     in_valid,
    input  logic [SYNDROME_BITS-1:0] syndrome,
    output logic                     out_valid,
    output logic                     correction
);
  localparam int Depth = 1 << SYNDROME_BITS;

  // Decoder lookup ROM: rom[s] = predicted logical-observable-0 flip for syndrome s.
  logic rom[Depth];
  initial $readmemb(MEM_FILE, rom);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_valid   <= 1'b0;
      correction  <= 1'b0;
    end else begin
      out_valid   <= in_valid;
      correction  <= in_valid ? rom[syndrome] : 1'b0;
    end
  end
endmodule
