// Q6-20 (part 2) — SLIDING-WINDOW STREAMING decoder: a thin wrapper around the per-window UF core
// (`uf_surface_decoder`) that decodes an unbounded stream of measurement rounds in bounded memory.
//
// A real QPU emits syndromes forever; you cannot store the whole history. The sliding-window approach
// (Dennis et al.; Skoric/Tan et al., and the software `SlidingWindowDecoder`, Q4-01) keeps a running
// residual of W rounds, decodes that window, COMMITS the oldest C rounds' correction, applies it to
// the residual (clearing the committed rounds), then slides forward by C and reloads C fresh rounds.
// Interior windows of a stream are translation-invariant, so ONE compiled window graph
// (`uf_surface_graph.svh`, generated by `qec_surface_uf_graph -- window <d> <W> <C>`, with the future
// time cut routed to temporal-sink nodes) serves every steady-state window, and the existing per-window
// core decodes it unchanged. This wrapper adds only the residual buffer, the per-edge commit, and the
// shift-by-C reload — the streaming control, in bounded `O(W)` state.
//
// Bit-for-bit equivalent to the software steady-state sliding decode (verified in tb_uf_streaming):
// the per-window decode, the "commit every chosen edge touching the commit region" rule, and the
// residual update are the identical operations, on the identical window graph.

`timescale 1ns / 1ps
`include "uf_surface_graph.svh"

module uf_streaming_decoder (
    input  logic               clk,
    input  logic               rst_n,
    // Stream input: present one measurement round of detector bits when `in_ready` is high.
    input  logic               in_valid,
    input  logic [UF_DPR-1:0]  in_round,
    output logic               in_ready,        // wrapper can accept a round this cycle
    // Streaming output: pulses once per committed window with that window's committed logical parity.
    output logic               out_valid,
    output logic               out_obs,
    output logic [15:0]        last_latency     // core decode latency of the last window (cycles)
);
  localparam int RESW = UF_ACTIVE;            // residual width (real detectors only)
  localparam int SYNW = UF_N - 1;             // core syndrome width (detectors 0..UF_N-2)
  localparam int PTRW = $clog2(UF_ACTIVE);    // load-cursor width (indexes res[UF_ACTIVE-1:0])

  typedef enum logic [2:0] { S_WARM, S_RUN, S_WAIT, S_COMMIT, S_SLIDE, S_RELOAD } state_t;
  state_t state;

  logic [RESW-1:0]  res;                      // residual syndrome over real detectors
  logic [PTRW-1:0]  lptr;                      // load cursor (detector index for the next streamed round)

  // ---- per-window core ----
  logic              core_iv;
  logic [SYNW-1:0]   core_syn;
  /* verilator lint_off UNUSEDSIGNAL */        // busy/obs unused: we wait on out_valid + recompute obs
  logic              core_busy, core_obs;
  /* verilator lint_on UNUSEDSIGNAL */
  logic              core_ov;
  logic [UF_M-1:0]   core_corr;
  logic [15:0]       core_lat;

  // sinks (UF_ACTIVE..UF_N-2) are never lit; pad the residual up to the core syndrome width.
  assign core_syn = SYNW'(res);

  uf_surface_decoder core (
      .clk(clk), .rst_n(rst_n),
      .in_valid(core_iv), .syndrome(core_syn),
      .busy(core_busy), .out_valid(core_ov),
      .correction(core_corr), .obs_flip(core_obs),
      .latency_cycles(core_lat)
  );

  // ---- combinational commit: from the core's chosen edges, the committed obs parity and the residual
  // toggle vector (XOR of every committed edge incident on each real detector). UF_ECOMMIT[e] marks an
  // edge touching the commit region; UF_EA/EB are its endpoints (a real detector is < UF_ACTIVE). ----
  logic              commit_obs;
  logic [RESW-1:0]   commit_tog;
  always_comb begin
    commit_obs = 1'b0;
    commit_tog = '0;
    for (int e = 0; e < UF_M; e++)
      if (core_corr[e] && UF_ECOMMIT[e]) begin
        commit_obs ^= UF_ELOG[e];
        if (UF_EA[e] < UF_ACTIVE) commit_tog[UF_EA[e]] ^= 1'b1;
        if (UF_EB[e] < UF_ACTIVE) commit_tog[UF_EB[e]] ^= 1'b1;
      end
  end

  // ---- slide-by-C: each residual bit carries to its post-slide index (UF_SHIFT), committed-and-
  // dropped bits (sentinel UF_ACTIVE) fall off, and the reload region [UF_LOAD_LO, UF_ACTIVE) is
  // cleared for the incoming C rounds. ----
  logic [RESW-1:0] res_slid;
  always_comb begin
    res_slid = '0;
    for (int d = 0; d < UF_ACTIVE; d++)
      if (UF_SHIFT[d] < UF_ACTIVE && res[d]) res_slid[UF_SHIFT[d]] = 1'b1;
  end

  assign in_ready = (state == S_WARM) || (state == S_RELOAD);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state        <= S_WARM;
      res          <= '0;
      lptr         <= '0;
      core_iv      <= 1'b0;
      out_valid    <= 1'b0;
      out_obs      <= 1'b0;
      last_latency <= '0;
    end else begin
      out_valid <= 1'b0;          // 1-cycle pulse
      core_iv   <= 1'b0;

      unique case (state)
        // Warm-up: load the first W rounds (detectors [0, UF_ACTIVE)) one round per cycle.
        S_WARM: begin
          if (in_valid) begin
            res[lptr +: UF_DPR] <= in_round;
            if (lptr + PTRW'(UF_DPR) >= PTRW'(UF_ACTIVE)) begin lptr <= '0; state <= S_RUN; end
            else                                          lptr <= lptr + PTRW'(UF_DPR);
          end
        end

        // Kick the per-window core on the current residual.
        S_RUN: begin
          core_iv <= 1'b1;
          state   <= S_WAIT;
        end

        S_WAIT: if (core_ov) begin
          last_latency <= core_lat;
          state        <= S_COMMIT;
        end

        // Apply the committed correction to the residual and emit the window's committed obs.
        S_COMMIT: begin
          res       <= res ^ commit_tog;   // clears the commit-region defects
          out_obs   <= commit_obs;
          out_valid <= 1'b1;
          state     <= S_SLIDE;
        end

        // Slide forward by C and clear the reload region.
        S_SLIDE: begin
          res   <= res_slid;
          lptr  <= PTRW'(UF_LOAD_LO);
          state <= S_RELOAD;
        end

        // Reload the C newest rounds into [UF_LOAD_LO, UF_ACTIVE), then decode the next window.
        S_RELOAD: begin
          if (in_valid) begin
            res[lptr +: UF_DPR] <= in_round;
            if (lptr + PTRW'(UF_DPR) >= PTRW'(UF_ACTIVE)) begin lptr <= '0; state <= S_RUN; end
            else                                          lptr <= lptr + PTRW'(UF_DPR);
          end
        end

        default: state <= S_WARM;
      endcase
    end
  end
endmodule
