//! Enumerates `oracle/fixtures/*.json` at compile time and emits one
//! `#[test]` per fixture into `$OUT_DIR/_generated.rs`. The test body
//! parses the matching QASM, runs it through `NaiveSvBackend`, and
//! delegates to `aleph_oracle::run_state_oracle`.
//!
//! Adding a new fixture is therefore a no-op on the Rust side — the
//! `cargo:rerun-if-changed` line below triggers regeneration.

use std::fmt::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Cheap self-test of the identifier validator. Build scripts can't
    // host `cargo test` cases, so we sanity-check the few obvious
    // properties here. The cost is negligible (one call each per build)
    // and catches a regression in is_valid_ident before any fixture
    // hits the codegen path.
    assert!(is_valid_ident("ghz_3"));
    assert!(is_valid_ident("kernel_h"));
    assert!(!is_valid_ident("match"));
    assert!(!is_valid_ident("fn"));
    assert!(!is_valid_ident(""));
    assert!(!is_valid_ident("1leading_digit"));

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let fixtures_dir = workspace_root.join("oracle/fixtures");

    println!("cargo:rerun-if-changed={}", fixtures_dir.display());

    let mut tests = String::from("// Generated by build.rs — do not edit.\n\n");

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&fixtures_dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", fixtures_dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    entries.sort();

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        if !is_valid_ident(&stem) {
            panic!(
                "fixture name {stem:?} is not a valid Rust identifier or is a Rust keyword. \
                 Rename `oracle/fixtures/{stem}.json` (and the matching .qasm) to something \
                 ASCII-alphanumeric that isn't a Rust keyword (e.g. prefix with `kernel_`)."
            );
        }
        let qasm = format!("oracle/circuits/{stem}.qasm");
        let json = format!("oracle/fixtures/{stem}.json");
        writeln!(
            tests,
            r#"
#[test]
fn {stem}() {{
    let fx = aleph_oracle::load_fixture(&aleph_oracle::workspace_path({json:?}))
        .expect("load fixture");
    let qasm = aleph_oracle::load_qasm(&aleph_oracle::workspace_path({qasm:?}))
        .expect("load qasm");
    let mut backend = aleph_sv::NaiveSvBackend::with_seed(0);
    aleph_oracle::run_state_oracle(&mut backend, &fx, &qasm).expect("oracle");
}}
"#
        )
        .unwrap();
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("_generated.rs");
    std::fs::write(&out_path, tests).expect("write _generated.rs");
}

fn is_valid_ident(s: &str) -> bool {
    // Reject Rust keywords (strict + reserved as of edition 2021).
    // Without this denylist a fixture named `match.json` would emit
    // `fn match() { ... }` and the test crate would fail to compile
    // with a parser error pointing at the auto-generated file rather
    // than at the offending fixture.
    const RUST_KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait",
        "true", "type", "unsafe", "use", "where", "while",
        // Reserved but currently unused.
        "abstract", "become", "box", "do", "final", "macro", "override", "priv", "try", "typeof",
        "unsized", "virtual", "yield",
    ];
    if RUST_KEYWORDS.contains(&s) {
        return false;
    }
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
}
