[package]
name = "aleph-sv"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
aleph-core    = { path = "../aleph-core" }
aleph-ir      = { path = "../aleph-ir" }
aleph-backend = { path = "../aleph-backend" }
rand          = { workspace = true }
smallvec      = { workspace = true }

[dev-dependencies]
aleph-parser = { path = "../aleph-parser" }
proptest     = { workspace = true }
criterion    = { workspace = true }

[[bench]]
name = "naive_sv"
harness = false

[[bench]]
name = "sample"
harness = false
