[package]
name = "aleph-cli"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "aleph"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
aleph-core    = { path = "../aleph-core" }
aleph-ir      = { path = "../aleph-ir" }
aleph-parser  = { path = "../aleph-parser" }
aleph-backend = { path = "../aleph-backend" }
aleph-sv      = { path = "../aleph-sv" }
clap          = { workspace = true }
anyhow        = { workspace = true }
thiserror     = { workspace = true }

[dev-dependencies]
aleph-oracle = { path = "../aleph-oracle" }
assert_cmd   = { workspace = true }
predicates   = { workspace = true }
proptest     = { workspace = true }
