//! Regression test: every Stage 0 QASM circuit parses cleanly.
//!
//! Files generated by `scripts/qiskit-baseline/run.py` and checked into the
//! repo.  If a future Qiskit version emits a gate aleph-parser doesn't
//! support, this test fails — we then either widen the parser or restrict
//! Qiskit's basis_gates list further.

use std::path::PathBuf;

fn fixture_path(name: &str) -> PathBuf {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("crate is two dirs deep from repo root")
        .to_path_buf();
    repo_root
        .join("scripts/qiskit-baseline/circuits")
        .join(name)
}

#[test]
fn parses_qft_n20() {
    let src = std::fs::read_to_string(fixture_path("qft_n20.qasm")).unwrap();
    let circuit = aleph_parser::parse(&src).expect("qft_n20.qasm must parse");
    assert_eq!(circuit.num_qubits(), 20);
    assert!(!circuit.is_empty());
}

#[test]
fn parses_grover_n20_iters5() {
    let src = std::fs::read_to_string(fixture_path("grover_n20_iters5.qasm")).unwrap();
    let circuit = aleph_parser::parse(&src).expect("grover_n20_iters5.qasm must parse");
    assert_eq!(circuit.num_qubits(), 20);
}

#[test]
fn parses_random_brickwall_n20_d20() {
    let src = std::fs::read_to_string(fixture_path("random_brickwall_n20_d20.qasm")).unwrap();
    let circuit =
        aleph_parser::parse(&src).expect("random_brickwall_n20_d20.qasm must parse");
    assert_eq!(circuit.num_qubits(), 20);
}
