"""Render docs/perf/surface_code.md from aleph + Stim JSON (deterministic, pure).
aleph JSON: {"workloads": {"3": {"d":3,"median_s":...}, ...}}.
Stim JSON: {"workloads": {"3": {"d":3,"qubits":17,"median_s":...}, ...}}."""
import argparse
import json
from pathlib import Path

CAVEAT = (
    "_Single-thread both sides. aleph = `StabilizerBackend` (CHP tableau, "
    "O(n²)); baseline = Stim `TableauSimulator`. One rotated surface-code "
    "syndrome-extraction cycle (2d²−1 qubits). **Stim is a purpose-built, "
    "heavily-optimised stabilizer simulator; aleph is expected to be slower "
    "per cycle** — the deliverable is correctness parity (postselected "
    "stabilizer-group equivalence, `surface_code_stim_oracle`) plus a "
    "documented time-per-cycle row, not beating Stim._"
)


def render(aleph: dict, stim: dict, meta: dict) -> str:
    out = [
        "# Phase 4 — Surface-code syndrome extraction (stabilizer)\n",
        "> Auto-generated by `scripts/surface_code/render_report.py`. Do not edit by hand.\n",
        f"**Date:** {meta['date']}  ",
        f"**Host:** {meta['host']}  ",
        f"**Toolchain:** {meta['toolchain']}\n",
        CAVEAT,
        "",
        "## Time per cycle\n",
        "| d | qubits | aleph (ms) | Stim (ms) | aleph / Stim |",
        "|--:|-------:|-----------:|----------:|-------------:|",
    ]
    for d in [3, 5, 7, 9, 11]:
        k = str(d)
        a = aleph["workloads"].get(k)
        s = stim["workloads"].get(k)
        if not a or not s:
            continue
        a_ms = a["median_s"] * 1000.0
        s_ms = s["median_s"] * 1000.0
        ratio = a_ms / s_ms if s_ms else float("nan")
        out.append(f"| {d} | {s['qubits']} | {a_ms:.3f} | {s_ms:.3f} | {ratio:.2f}× |")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--aleph", required=True, type=Path)
    ap.add_argument("--stim", required=True, type=Path)
    ap.add_argument("--meta", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()
    aleph = json.loads(args.aleph.read_text())
    stim = json.loads(args.stim.read_text())
    meta = json.loads(args.meta.read_text())
    args.out.write_text(render(aleph, stim, meta))


if __name__ == "__main__":
    main()
